# Deploy a stack of Java micro-services to a swarm cluster
# 3 stages: 
#   1- init : Initiate the Docker Swarm Cluster and create a Docker Registry service
#   2- buid : Create the Docker Stack using Docker-Compose and Traefik
#   3- deploy: Deploy the Stack to Docker-Swarm Cluster

stages:
 - init
 - build
 - deploy
 
init-swarm:
 stage: init
 script:
 - docker swarm init
 - docker service create --name registry --publish published=5000,target=5000 registry:2
 
build:
 stage: build
 script:
 - cd /docker && docker-compose up -d
 - cd /docker && docker-compose down --volume
 - cd /docker && docker-compose push
 
deploy-containers:
 stage: deploy
 script:
 - cd docker/ && docker stack deploy --compose-file docker-compose.yml stackdemo