version: '3'

services:

  traefik:
    image: traefik:1.3.4
    command: -l warning --docker --docker.swarmmode --docker.domain=docker.localhost --docker.watch --web
    ports:
      - '80:80'
#      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    networks:
      - net
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "false"


networks:
  net:
    driver: overlay
